name: "Manual Build"

on:
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  delete-old-manual:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Manual Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: manual
          delete_release: true
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-tauri:
    needs: delete-old-manual
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""


    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Read CHANGELOG
        id: changelog
        shell: bash
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            content=$(base64 < CHANGELOG.MD | tr -d '\n')
          else
            # Linux
            content=$(base64 -w 0 CHANGELOG.MD)
          fi
          echo "content=${content}" >> $GITHUB_OUTPUT

      - name: Decode CHANGELOG
        id: decode
        shell: bash
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            content=$(echo "${{ steps.changelog.outputs.content }}" | base64 -D)
          else
            # Linux
            content=$(echo "${{ steps.changelog.outputs.content }}" | base64 -d)
          fi
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Tauri Version
        id: tauri_version
        run: echo "version=$(node -p "require('./src-tauri/tauri.conf.json').version")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set Up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Frontend Dependencies
        run: bun install

      - name: Download Binaries
        run: bun run scripts/download-binaries.ts

      - name: Build and Release with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: "manual"
          releaseName: "Manual"
          releaseBody: |
            ${{ steps.decode.outputs.content }}
          args: ${{ matrix.args }}
          prerelease: true